# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bimage.proto\x12\x05image\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x1e\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\x0c\"7\n\x15\x46\x61\x63\x65SimilarityRequest\x12\x0e\n\x06image1\x18\x01 \x01(\x0c\x12\x0e\n\x06image2\x18\x02 \x01(\x0c\",\n\x16\x46\x61\x63\x65SimilarityResponse\x12\x12\n\nsimilarity\x18\x01 \x01(\x02\x32\xd2\x01\n\x0eImageProcessor\x12\x34\n\x07GetGray\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponse\x12\x38\n\x0bGetCropFace\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponse\x12P\n\x11GetFaceSimilarity\x12\x1c.image.FaceSimilarityRequest\x1a\x1d.image.FaceSimilarityResponseb\x06proto3')



_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_IMAGERESPONSE = DESCRIPTOR.message_types_by_name['ImageResponse']
_FACESIMILARITYREQUEST = DESCRIPTOR.message_types_by_name['FaceSimilarityRequest']
_FACESIMILARITYRESPONSE = DESCRIPTOR.message_types_by_name['FaceSimilarityResponse']
ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageResponse = _reflection.GeneratedProtocolMessageType('ImageResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMAGERESPONSE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.ImageResponse)
  })
_sym_db.RegisterMessage(ImageResponse)

FaceSimilarityRequest = _reflection.GeneratedProtocolMessageType('FaceSimilarityRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACESIMILARITYREQUEST,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.FaceSimilarityRequest)
  })
_sym_db.RegisterMessage(FaceSimilarityRequest)

FaceSimilarityResponse = _reflection.GeneratedProtocolMessageType('FaceSimilarityResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACESIMILARITYRESPONSE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:image.FaceSimilarityResponse)
  })
_sym_db.RegisterMessage(FaceSimilarityResponse)

_IMAGEPROCESSOR = DESCRIPTOR.services_by_name['ImageProcessor']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREQUEST._serialized_start=22
  _IMAGEREQUEST._serialized_end=51
  _IMAGERESPONSE._serialized_start=53
  _IMAGERESPONSE._serialized_end=83
  _FACESIMILARITYREQUEST._serialized_start=85
  _FACESIMILARITYREQUEST._serialized_end=140
  _FACESIMILARITYRESPONSE._serialized_start=142
  _FACESIMILARITYRESPONSE._serialized_end=186
  _IMAGEPROCESSOR._serialized_start=189
  _IMAGEPROCESSOR._serialized_end=399
# @@protoc_insertion_point(module_scope)
