# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.grpc_server.image_pb2 as image__pb2


class ImageProcessorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetGray = channel.unary_unary(
                '/image.ImageProcessor/GetGray',
                request_serializer=image__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__pb2.ImageResponse.FromString,
                )
        self.GetCropFace = channel.unary_unary(
                '/image.ImageProcessor/GetCropFace',
                request_serializer=image__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__pb2.ImageResponse.FromString,
                )
        self.GetKotenOCR = channel.unary_unary(
                '/image.ImageProcessor/GetKotenOCR',
                request_serializer=image__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__pb2.KotenOCR_Response.FromString,
                )
        self.GetFaceSimilarity = channel.unary_unary(
                '/image.ImageProcessor/GetFaceSimilarity',
                request_serializer=image__pb2.FaceSimilarityRequest.SerializeToString,
                response_deserializer=image__pb2.FaceSimilarityResponse.FromString,
                )


class ImageProcessorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetGray(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCropFace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetKotenOCR(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFaceSimilarity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageProcessorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetGray': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGray,
                    request_deserializer=image__pb2.ImageRequest.FromString,
                    response_serializer=image__pb2.ImageResponse.SerializeToString,
            ),
            'GetCropFace': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCropFace,
                    request_deserializer=image__pb2.ImageRequest.FromString,
                    response_serializer=image__pb2.ImageResponse.SerializeToString,
            ),
            'GetKotenOCR': grpc.unary_unary_rpc_method_handler(
                    servicer.GetKotenOCR,
                    request_deserializer=image__pb2.ImageRequest.FromString,
                    response_serializer=image__pb2.KotenOCR_Response.SerializeToString,
            ),
            'GetFaceSimilarity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFaceSimilarity,
                    request_deserializer=image__pb2.FaceSimilarityRequest.FromString,
                    response_serializer=image__pb2.FaceSimilarityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'image.ImageProcessor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageProcessor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetGray(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageProcessor/GetGray',
            image__pb2.ImageRequest.SerializeToString,
            image__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCropFace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageProcessor/GetCropFace',
            image__pb2.ImageRequest.SerializeToString,
            image__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetKotenOCR(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageProcessor/GetKotenOCR',
            image__pb2.ImageRequest.SerializeToString,
            image__pb2.KotenOCR_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetFaceSimilarity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/image.ImageProcessor/GetFaceSimilarity',
            image__pb2.FaceSimilarityRequest.SerializeToString,
            image__pb2.FaceSimilarityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
